### PR TITLE
startOf/endOf

### PR DESCRIPTION
**Pull request by artknight**

### CODE REVIEW

**Comment by atuttle** [comment]
Thanks for the contribution! What's the difference between this PR and #16? Accidental duplicates? Maybe that one is after you merged upstream changes? (I see a few additional changes in #16, not included here, that I think I had made not too long ago)

Once we get that sorted out, and I can set aside some time to update the documentation, I'm excited to merge this in!

**Comment by artknight** [comment]
In #16 I had an older copy of moment and thus some of the changes were actually removing some code. I corrected it in #17. You can delete that PR (#16).

**Comment by artknight** [comment]
Also, on line 180 I had to change `this.localTime` to `this.time` otherwise it was returning incorrect time.

**Comment by atuttle** [comment]
Thanks for the clarifications. I'll try to get this merged as soon as possible!

**Comment by atuttle** [comment]
Turned out you had some logic bugs. That time vs localTime thing was a clue. 😃 

No worries, I figured it out. Thanks again for the contribution!

**Comment by artknight** [comment]
Awesome, Thanks Adam! Quick question, why did you re-write my `endOf` method?

**Comment by atuttle** [comment]
It was failing the tests.

**Pull request merged**
